apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: "cert-manager-{{name}}"
      labels:
        environment: prd
    spec:
      project: default
      source:
        helm:
          releaseName: "cert"
          valueFiles:
            - "values.yml"
            - "values-{{name}}.yml"
        path: ./
        repoURL: git@github.com:1oopio/argocd-appset-cert-manager
        targetRevision: HEAD
      destination:
        server: "{{server}}"
        namespace: cert-manager
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
