apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-dns
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: "external-dns-{{name}}"
      labels:
        environment: prd
    spec:
      project: default
      source:
        helm:
          releaseName: "dns"
          valueFiles:
            - "values.yml"
            - "values-{{name}}.yml"
        path: ./
        repoURL: git@github.com:1oopio/argocd-appset-external-dns
        targetRevision: HEAD
      destination:
        server: "{{server}}"
        namespace: external-dns
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
