apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: "ingress-nginx-{{name}}"
      labels:
        environment: prd
    spec:
      project: default
      source:
        helm:
          releaseName: "nginx"
          valueFiles:
            - "values.yml"
            - "values-{{name}}.yml"
        path: ./
        repoURL: git@github.com:1oopio/argocd-appset-ingress-nginx
        targetRevision: HEAD
      destination:
        server: "{{server}}"
        namespace: ingress-nginx
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
