apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: keycloak
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            mgmt-cluster: "true"
  template:
    metadata:
      name: "keycloak-{{name}}"
      labels:
        environment: prd
    spec:
      project: default
      source:
        helm:
          releaseName: "keycloak"
          valueFiles:
            - "values.yml"
        path: ./
        repoURL: git@github.com:1oopio/argocd-appset-keycloak
        targetRevision: HEAD
      destination:
        server: "{{server}}"
        namespace: keycloak
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
