apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: phantomias-dev
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            mgmt-cluster: "true"
  template:
    metadata:
      name: "phantomias-{{name}}"
      labels:
        environment: prod
    spec:
      project: default
      source:
        helm:
          releaseName: "phantomias"
          valueFiles:
            - "values.yml"
            - "values-{{name}}.yml"
        path: ./
        repoURL: git@github.com:1oopio/argocd-appset-phantomias-dev
        targetRevision: HEAD
      destination:
        server: "{{server}}"
        namespace: miningcore-dev
      syncPolicy:
        syncOptions:
          - CreateNamespace=true