apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prom
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: "prom-{{name}}"
      labels:
        environment: prd
    spec:
      project: default
      source:
        helm:
          skipCrds: true
          releaseName: "prom"
          valueFiles:
            - "values-{{name}}.yml"
        path: ./
        repoURL: git@github.com:1oopio/argocd-appset-prom
        targetRevision: HEAD
      destination:
        server: "{{server}}"
        namespace: monitoring
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
