apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prom-crd
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: "prom-crd-{{name}}"
      labels:
        environment: prd
    spec:
      project: default
      source:
        repoURL: https://github.com/prometheus-community/helm-charts.git
        path: charts/kube-prometheus-stack/crds/
        targetRevision: kube-prometheus-stack-43.1.4
        directory:
          recurse: true
      destination:
        server: "{{server}}"
        namespace: monitoring
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - Replace=true
