apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: "sealed-secrets-{{name}}"
      labels:
        environment: prd
    spec:
      project: default
      source:
        helm:
          releaseName: sealed-secrets
        repoURL: https://bitnami-labs.github.io/sealed-secrets
        chart: sealed-secrets
        targetRevision: 2.7.2
      destination:
        server: "{{server}}"
        namespace: kube-system
      syncPolicy:
        syncOptions:
          - CreateNamespace=true