apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: secretes
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: "secretes-{{name}}"
      labels:
        environment: prd
    spec:
      project: default
      source:
        path: secrets/prod/{{name}}
        repoURL: git@github.com:1oopio/argocd-appset-secrets
        targetRevision: HEAD
        directory:
          recurse: true
      destination:
        server: "{{server}}"
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
